### ISSUE TITLE
THIS IS THE WORST CODE I HAVE EVER SEEN

### ISSUE THREAD

**Issue by RohanOpenSource** [godatcp/coolthings#2]
This code makes me so sad that I cry!!!

**Comment by godatcp** [comment]
how to make code gud. also how gitgud at doing the code in scratch

**Comment by RohanOpenSource** [comment]
MAKE A NEW METHOD FOR EVERYTHING CAN YOU EVEN CODE!?!?

**Comment by godatcp** [comment]
No I do sCRATh With NODE JS WRAPPER POGCHAMp

**Comment by dude123studios** [comment]
i done
